name: "testes regressivos"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'

jobs:
  test-linux:
    name: Playwright@${{ matrix.browser}} ${{ matrix.os }} headless=${{ matrix.headless }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        playwright: [1.12.0]
        headless: [false]
        browser: [chrome,firefox,msedge,safari,chromium]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install operating system dependencies
      run: npx playwright install-deps |
       npm install -g allure-commandline --save-dev
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1.5.0
    - name: Install Media Pack
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: Install-WindowsFeature Server-Media-Foundation
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    #- name: Download drivers
      #shell: bash
      #run: scripts/download_driver_for_all_platforms.sh
    - name: Build with Maven
      run: mvn -B package -D skipTests --no-transfer-progress
    - name: Run tests
      if: always()
      continue-on-error: true
      run: mvn test -DbrowserType=${{ matrix.browser }} --no-transfer-progress
      env:
        BROWSER: chromium
        BROWSER_CHANNEL: ${{ matrix.browser-channel }}
    - name: 📊 Step 5 - Collect Allure files and generate allure-report folder
      run: |
        allure generate ./target/allure-results -o allure-report/
    - name: 🎁 Step 6 - Publishing Allure artifact to GitHub Actions
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # default: gh-pages
        publish_dir: allure-report
        destination_dir: ${{ matrix.browser}}
